export const siteOne = {
  id: 'so164652-c0ef-4991-b7cc-474cc0ea911',
  title: 'SiteOne Q1 2023',
  audioUrl: `https://${process.env.VERCEL_URL}/so164652-c0ef-4991-b7cc-474cc0ea911.ogg`,
  blocks: [
    {
      end: 15.64,
      speaker: 'Operator ',
      start: 0,
      text: 'At this time, all participants are in a listen-only mode.',
    },
    {
      end: 20.44,
      speaker: 'Operator ',
      start: 15.64,
      text: 'A brief question-and-answer session will follow the formal presentation.',
    },
    {
      end: 28.44,
      speaker: 'Operator ',
      start: 20.44,
      text: 'If anyone should require operator assistance during the conference, please press star zero on your telephone keypad.',
    },
    {
      end: 31.64,
      speaker: 'Operator ',
      start: 28.44,
      text: 'As a reminder, this conference is being recorded.',
    },
    {
      end: 39.24,
      speaker: 'Operator ',
      start: 31.64,
      text: "It's now my pleasure to introduce your host, John Guthrie, Executive Vice President and Chief Financial Officer.",
    },
    {
      end: 42.8,
      speaker: 'Operator ',
      start: 39.24,
      text: 'Please go ahead.',
    },
    {
      end: 44.64,
      speaker: 'John Guthrie, Executive Vice President and Chief Financial Officer.',
      start: 42.8,
      text: 'Thank you and good morning, everyone.',
    },
    {
      end: 55.96,
      speaker: 'John Guthrie, Executive Vice President and Chief Financial Officer.',
      start: 44.64,
      text: 'We issued our first quarter 2023 earned express release this morning and posted a slide presentation to the investor relations portion of our website at investors.site1.com.',
    },
    {
      end: 64.8,
      speaker: 'John Guthrie, Executive Vice President and Chief Financial Officer.',
      start: 55.96,
      text: "I'm joined today by Doug Black, our Chairman and Chief Executive Officer, and Scott Salmon, Executive Vice President Strategy and Development.",
    },
    {
      end: 78.08,
      speaker: 'John Guthrie, Executive Vice President and Chief Financial Officer.',
      start: 64.8,
      text: "Before we begin, I would like to remind everyone that today's press release slide presentation and the statements made during the call include forward-looking statements within the meaning of the Private Securities Litigation Reform Act of 1995.",
    },
    {
      end: 87.84,
      speaker: 'John Guthrie, Executive Vice President and Chief Financial Officer.',
      start: 78.08,
      text: 'These statements are subject to risks and uncertainties that could cause actual results to differ materially from our expectations and projections.',
    },
    {
      end: 97.28,
      speaker: 'John Guthrie, Executive Vice President and Chief Financial Officer.',
      start: 87.84,
      text: 'Such risks and uncertainties include the factors set forth in the earnings press release and in our violins with the Securities and Exchange Commission.',
    },
    {
      end: 106,
      speaker: 'John Guthrie, Executive Vice President and Chief Financial Officer.',
      start: 97.28,
      text: "Additionally, during today's call, we will discuss non-GAP measures, which we believe can be useful in evaluating our performance.",
    },
    {
      end: 111.44,
      speaker: 'John Guthrie, Executive Vice President and Chief Financial Officer.',
      start: 106,
      text: 'A reconciliation of these measures can be found in our earnings release and in the slide presentation.',
    },
    {
      end: 115.48,
      speaker: 'John Guthrie, Executive Vice President and Chief Financial Officer.',
      start: 111.44,
      text: 'I would now like to turn the call over to Doug Black.',
    },
    {
      end: 120.56,
      speaker: 'Doug Black, CEO',
      start: 115.48,
      text: 'Good morning, and thank you for joining us today.',
    },
    {
      end: 139.4,
      speaker: 'Doug Black, CEO',
      start: 120.56,
      text: 'Against the headwinds of a very strong prior year period, poor weather in the west and north, and moderating market demand, we executed well in the first quarter, delivering top-line growth and gross margin expansion along with a solid EBDA outcome in this traditionally low-volume quarter.',
    },
    {
      end: 146.56,
      speaker: 'Doug Black, CEO',
      start: 139.4,
      text: 'We were also very pleased to add two new high-performing companies to Site One during the first quarter.',
    },
    {
      end: 156.6,
      speaker: 'Doug Black, CEO',
      start: 146.56,
      text: 'These companies have talented teams and strong customer relationships, and they expand our product lines and market presence in their respective markets.',
    },
    {
      end: 171.76,
      speaker: 'Doug Black, CEO',
      start: 156.6,
      text: 'Through the execution of our commercial and operational initiatives and our acquisition strategy, we continue to build Site One as a world-class market leader for the long term while delivering consistent performance and growth in the near term.',
    },
    {
      end: 189.08,
      speaker: 'Doug Black, CEO',
      start: 171.76,
      text: 'As we face softer markets, we remain confident that our well-balanced business, strong balance sheet, exceptional teams, improved capabilities, and robust acquisition pipeline position us well to navigate the current environment and achieve continued success.',
    },
    {
      end: 200.52,
      speaker: 'Doug Black, CEO',
      start: 189.08,
      text: "I'll start today's call with a brief review of our unique market position and our strategy for long-term performance and growth, followed by some highlights from the quarter.",
    },
    {
      end: 209.92000000000002,
      speaker: 'Doug Black, CEO',
      start: 200.52,
      text: 'John Guthrie will then walk you through our first quarter financial results in more detail and provide an update on our balance sheet and liquidity position.',
    },
    {
      end: 220.12,
      speaker: 'Doug Black, CEO',
      start: 209.92000000000002,
      text: 'Scott Salmon will discuss our acquisition strategy, and then I will come back to address our latest outlook for 2023 before taking your questions.',
    },
    {
      end: 234.24,
      speaker: 'Doug Black, CEO',
      start: 220.12,
      text: "As shown on slide four of the earnings presentation, we've grown our footprint to more than 640 branches and four distribution centers across 45 U.S. states and six Canadian provinces.",
    },
    {
      end: 253,
      speaker: 'Doug Black, CEO',
      start: 234.24,
      text: 'We are the clear industry leader over four times the size of our nearest competitor, yet we estimate that we only have about a 16% share of the very fragmented $25 billion wholesale landscaping products distribution market.',
    },
    {
      end: 257.44,
      speaker: 'Doug Black, CEO',
      start: 253,
      text: 'Accordingly, our future growth opportunities remain significant.',
    },
    {
      end: 272.40000000000003,
      speaker: 'Doug Black, CEO',
      start: 257.44,
      text: 'We have a balanced mix of business with 65% focused on maintenance, repair, and upgrade, 21% focused on new residential construction, and 14% on new commercial and recreational construction.',
    },
    {
      end: 283.88,
      speaker: 'Doug Black, CEO',
      start: 272.40000000000003,
      text: 'As the only national full product line wholesale distributor in the market, we also have an excellent balance across our product lines as well as geographically.',
    },
    {
      end: 293.8,
      speaker: 'Doug Black, CEO',
      start: 283.88,
      text: 'Our strategy to fill in our product lines across the U.S. and Canada, both organically and through acquisition, strengthens and reinforces this balance over time.',
    },
    {
      end: 309.84000000000003,
      speaker: 'Doug Black, CEO',
      start: 293.8,
      text: 'Overall, our balanced end market mix, broad product portfolio, and good geographic coverage offer us multiple avenues to grow and create value for our customers and suppliers while providing important resiliency and softer markets.',
    },
    {
      end: 329.64000000000004,
      speaker: 'Doug Black, CEO',
      start: 309.84000000000003,
      text: 'Turning to slide five, our strategy is to leverage the scale, resources, functional talent, and capabilities that we have as the largest company in our industry, all in support of our talented, experienced, and entrepreneurial level teams to consistently deliver superior value to our customers and suppliers.',
    },
    {
      end: 340.47999999999996,
      speaker: 'Doug Black, CEO',
      start: 329.64000000000004,
      text: "We've come a long way in building Site One and executing our strategy, but we were relatively early in our development as a true world-class company.",
    },
    {
      end: 350.2,
      speaker: 'Doug Black, CEO',
      start: 340.47999999999996,
      text: 'Accordingly, we remain highly focused on our commercial and operational initiatives to further build our capability to create value for all our stakeholders.',
    },
    {
      end: 362.2,
      speaker: 'Doug Black, CEO',
      start: 350.2,
      text: 'These initiatives are complemented by our acquisition strategy, which fills in our product portfolio, moves us into new geographic markets, and adds terrific new talent to Site One.',
    },
    {
      end: 371.64,
      speaker: 'Doug Black, CEO',
      start: 362.2,
      text: 'Taken all together, our strategy creates superior value for our shareholders through organic growth, acquisition growth, and EBITDA margin expansion.',
    },
    {
      end: 384.52,
      speaker: 'Doug Black, CEO',
      start: 371.64,
      text: 'Turning to slide six, you can see our strong track record of performance and growth over the last seven years with consistent organic and acquisition growth and EBITDA margin expansion.',
    },
    {
      end: 396.71999999999997,
      speaker: 'Doug Black, CEO',
      start: 384.52,
      text: 'We have done this while investing heavily in our teams and in new systems and technologies to build the foundation for Site One and to create superior capabilities for our customers and suppliers.',
    },
    {
      end: 407.79999999999995,
      speaker: 'Doug Black, CEO',
      start: 396.71999999999997,
      text: "We're still building and investing, and we remain confident in our ability to gain market share and continue driving all three of our value creation levers going forward.",
    },
    {
      end: 416.16,
      speaker: 'Doug Black, CEO',
      start: 407.79999999999995,
      text: 'We have now completed 82 acquisitions across all key product lines since 2014.',
    },
    {
      end: 426.36,
      speaker: 'Doug Black, CEO',
      start: 416.16,
      text: 'We leveraged our expanded development team to increase acquisition activity this past year, and our pipeline and potential deals remains robust.',
    },
    {
      end: 434.56,
      speaker: 'Doug Black, CEO',
      start: 426.36,
      text: 'All these companies are high performers, and so they strengthen our company with excellent talent and new ideas for performance and growth.',
    },
    {
      end: 444.76,
      speaker: 'Doug Black, CEO',
      start: 434.56,
      text: 'Given the fragmented nature of our industry and our modest market share, we have significant opportunity to continue growing through acquisition for many years to come.',
    },
    {
      end: 457.32,
      speaker: 'Doug Black, CEO',
      start: 444.76,
      text: 'Slide seven shows the long runway that we have ahead in filling in our product portfolio, which we aim to do primarily through acquisition, especially in the nursery, parkscapes, and landscape supplies categories.',
    },
    {
      end: 467.92,
      speaker: 'Doug Black, CEO',
      start: 457.32,
      text: 'We are well-networked with the best companies in our industry and expect to continue filling in these markets systematically over the next decade.',
    },
    {
      end: 473.08,
      speaker: 'Doug Black, CEO',
      start: 467.92,
      text: 'I will now discuss some of our first quarter performance highlights as shown on slide eight.',
    },
    {
      end: 487.56,
      speaker: 'Doug Black, CEO',
      start: 473.08,
      text: 'We achieved 4% net sales growth in the first quarter, as the 7% net sales growth added through acquisition was partially offset by an organic daily sales decline of 2%.',
    },
    {
      end: 503.04,
      speaker: 'Doug Black, CEO',
      start: 487.56,
      text: 'Note that organic daily sales grew 32% in the first quarter of 2021, largely driven by volume, and grew 17% in the first quarter of 2022, largely driven by price inflation.',
    },
    {
      end: 509.08000000000004,
      speaker: 'Doug Black, CEO',
      start: 503.04,
      text: 'So in terms of sales, Q1 is our toughest comparable for 2023.',
    },
    {
      end: 521.24,
      speaker: 'Doug Black, CEO',
      start: 509.08000000000004,
      text: 'Accordingly, we were pleased that the organic daily sales decline was only 2%, driven by 6% price inflation, which was offset by an 8% volume decline.',
    },
    {
      end: 533.3199999999999,
      speaker: 'Doug Black, CEO',
      start: 521.24,
      text: 'We experienced the most significant volume declines in our western markets that had record rainfall and in our northern markets where spring came later than in 2022.',
    },
    {
      end: 543.8,
      speaker: 'Doug Black, CEO',
      start: 533.3199999999999,
      text: 'Where the weather was more favorable in the southeast, mid-Atlantic, and Florida, we saw high single-digit to low double-digit organic daily sales growth during the first quarter.',
    },
    {
      end: 557.16,
      speaker: 'Doug Black, CEO',
      start: 543.8,
      text: 'We have also seen the spring season kick into gear during April, which has increased our year-to-date organic daily sales growth to approximately 1% through the first four weeks in April.',
    },
    {
      end: 570.4,
      speaker: 'Doug Black, CEO',
      start: 557.16,
      text: 'Our gross profit increased 7%, and our gross margin increased 90 basis points for a very healthy 34.3%, even as inflation continued to moderate through the quarter.',
    },
    {
      end: 588.64,
      speaker: 'Doug Black, CEO',
      start: 570.4,
      text: 'The loss of the extraordinary price realization benefit achieved during the first quarter of 2022 was more than offset by our hardscapes and landscape supplies acquisitions, which carry a higher gross margin, and by lower fuel cost and some price cost benefit.',
    },
    {
      end: 603.9200000000001,
      speaker: 'Doug Black, CEO',
      start: 588.64,
      text: 'Despite the strong start with gross margin in the quarter, we continue to expect gross margin for the full year to be lower than in 2022, but perhaps stronger than we had thought at the beginning of the year.',
    },
    {
      end: 619.0799999999999,
      speaker: 'Doug Black, CEO',
      start: 603.9200000000001,
      text: 'Our EDG&A as a percentage of net sales increased by 620 basis points year over year to 34.8%, which is a 60 basis point increase compared to the fourth quarter of 2022.',
    },
    {
      end: 629.7199999999999,
      speaker: 'Doug Black, CEO',
      start: 619.0799999999999,
      text: 'Acquisitions had the largest effect on EDG&A as a percentage of net sales, as the same hardscapes and landscape supplies acquisitions that increased our gross margin also increased our EDG&A.',
    },
    {
      end: 640.68,
      speaker: 'Doug Black, CEO',
      start: 629.7199999999999,
      text: 'Additionally, several of these acquisitions were in the west and north, where poor weather and a late spring caused further deleveraging in the quarter.',
    },
    {
      end: 648.04,
      speaker: 'Doug Black, CEO',
      start: 640.68,
      text: 'Lower volume and continued labor inflation were also factors contributing to the higher SG&A as a percent of net sales.',
    },
    {
      end: 669.36,
      speaker: 'Doug Black, CEO',
      start: 648.04,
      text: 'Adjusted EBGA for the quarter declined 41% to 39.8 million, and adjusted EBGA margin declined by 360 basis points to 4.8%, as the combination of lower volume and higher SG&A yielded a more typical first quarter adjusted EBGA outcome.',
    },
    {
      end: 684.16,
      speaker: 'Doug Black, CEO',
      start: 669.36,
      text: 'Note that adjusted EBGA during the first quarter of 2022 had increased 97% from the first quarter of 2021, reflecting strong organic sales and elevated gross margin.',
    },
    {
      end: 690,
      speaker: 'Doug Black, CEO',
      start: 684.16,
      text: 'Overall, adjusted EBGA in the first quarter was in line with our expectations.',
    },
    {
      end: 697.08,
      speaker: 'Doug Black, CEO',
      start: 690,
      text: 'In terms of initiatives, we are pleased with our progress as we enter the busiest time of our year.',
    },
    {
      end: 711.6800000000001,
      speaker: 'Doug Black, CEO',
      start: 697.08,
      text: 'Continue to grow with our small and medium customers, drive private label growth, and improve our inbound freight costs through our transportation management system, all helping us to expand our gross margin.',
    },
    {
      end: 730.04,
      speaker: 'Doug Black, CEO',
      start: 711.6800000000001,
      text: 'Our driving organic growth through our enhanced partners program, our Hispanic marketing initiatives, and as we leverage our recently installed Salesforce CRM to drive stronger sales and better productivity from our team of more than 900 inside and outside sellers.',
    },
    {
      end: 742.84,
      speaker: 'Doug Black, CEO',
      start: 730.04,
      text: 'Continued rollout of MobilePro and DispatchTrack allows us to offer better customer service while also increasing the productivity of our branch staff and delivery fleet.',
    },
    {
      end: 755.68,
      speaker: 'Doug Black, CEO',
      start: 742.84,
      text: 'Continue to ramp up our digital sales and other customer activities through SiteOne.com, which makes our customers and associates more productive and helps us to gain market share.',
    },
    {
      end: 767.56,
      speaker: 'Doug Black, CEO',
      start: 755.68,
      text: 'Finally, our operational excellence teams are systematically spreading best practices in each line of business across SiteOne to drive value for our customers, suppliers, and company.',
    },
    {
      end: 778.36,
      speaker: 'Doug Black, CEO',
      start: 767.56,
      text: 'Taken all together, we have significantly improved our capability to perform through the potential headwinds of 2023.',
    },
    {
      end: 790.5600000000001,
      speaker: 'Doug Black, CEO',
      start: 778.36,
      text: 'On the acquisition front, we added two high-performing companies to our family so far this year, adding approximately 40 million in trailing 12-month sales to SiteOne.',
    },
    {
      end: 804,
      speaker: 'Doug Black, CEO',
      start: 790.5600000000001,
      text: 'Following a record number of acquisitions in 2022, our expanded development team remains very active and engaged with our pipeline of targets, and we expect to have another robust acquisition year in 2023.',
    },
    {
      end: 819.16,
      speaker: 'Doug Black, CEO',
      start: 804,
      text: 'With an experienced team, broad and deep relationships with the best companies, a strong balance sheet, and an exceptional reputation, we remain well-positioned to grow consistently through acquisition this year and for many years to come.',
    },
    {
      end: 826.72,
      speaker: 'Doug Black, CEO',
      start: 819.16,
      text: 'In summary, we were off to a good start in navigating the more challenging market conditions in 2023.',
    },
    {
      end: 838,
      speaker: 'Doug Black, CEO',
      start: 826.72,
      text: 'I am pleased with our progress and remain confident in our ability to execute our initiatives and deliver increased value to our customers and suppliers while outperforming the market.',
    },
    {
      end: 842.4399999999999,
      speaker: 'Doug Black, CEO',
      start: 838,
      text: 'Now, John will walk you through the quarter in more detail.',
    },
    {
      end: 843.4399999999999,
      speaker: 'Doug Black, CEO',
      start: 842.4399999999999,
      text: 'John?',
    },
    {
      end: 844.4399999999999,
      speaker: 'John Guthrie, Executive Vice President and Chief Financial Officer',
      start: 843.4399999999999,
      text: 'Thanks, Doug.',
    },
    {
      end: 851,
      speaker: 'John Guthrie, Executive Vice President and Chief Financial Officer.',
      start: 844.4399999999999,
      text: "I'll begin on slide nine with some highlights of our first quarter results.",
    },
    {
      end: 856.92,
      speaker: 'John Guthrie, Executive Vice President and Chief Financial Officer.',
      start: 851,
      text: 'We reported a net sales increase of 4% to 837 million for the quarter.',
    },
    {
      end: 864.88,
      speaker: 'John Guthrie, Executive Vice President and Chief Financial Officer.',
      start: 856.92,
      text: 'There were 64 selling days in the first quarter, which is one less day than we had in the first quarter of 2022.',
    },
    {
      end: 874.28,
      speaker: 'John Guthrie, Executive Vice President and Chief Financial Officer.',
      start: 864.88,
      text: 'Organic daily sales decreased by 2% in the first quarter as sales volume was negatively impacted by weather and moderating economic conditions.',
    },
    {
      end: 880.52,
      speaker: 'John Guthrie, Executive Vice President and Chief Financial Officer.',
      start: 874.28,
      text: 'Price inflation contributed approximately 6% to organic daily sales growth for the quarter.',
    },
    {
      end: 892.32,
      speaker: 'John Guthrie, Executive Vice President and Chief Financial Officer.',
      start: 880.52,
      text: 'As we discussed last quarter, we are seeing less price inflation as we count the large price increases of last year and the cost for products like fertilizer and PVC pipe decrease.',
    },
    {
      end: 902.48,
      speaker: 'John Guthrie, Executive Vice President and Chief Financial Officer.',
      start: 892.32,
      text: 'For the full year, we continue to expect price inflation in the low single digits with the majority of it realized in the first half of the year.',
    },
    {
      end: 909.6,
      speaker: 'John Guthrie, Executive Vice President and Chief Financial Officer.',
      start: 902.48,
      text: 'Volume declined 8% for the first quarter as cold and rainy weather in our western and northern markets reduced demand.',
    },
    {
      end: 918.16,
      speaker: 'John Guthrie, Executive Vice President and Chief Financial Officer.',
      start: 909.6,
      text: 'Western markets, and especially California, were negatively impacted by unprecedented precipitation during the quarter.',
    },
    {
      end: 925.88,
      speaker: 'John Guthrie, Executive Vice President and Chief Financial Officer.',
      start: 918.16,
      text: 'Organic daily sales for California, one of the largest landscaping markets in the U.S., were down 21%.',
    },
    {
      end: 934.96,
      speaker: 'John Guthrie, Executive Vice President and Chief Financial Officer.',
      start: 925.88,
      text: 'Organic daily sales in our northern markets were also negatively impacted by weather as the late start to spring delayed fertilizer applications and limited snow and ice events',
    },
    {
      end: 947.88,
      speaker: 'John Guthrie, Executive Vice President and Chief Financial Officer',
      start: 934.96,
      text: 'reduced demand for ice milk. Fortunately, we have a geographically diverse customer base and the negative sales growth in western and northern markets was partially offset by solid growth in our southern markets.',
    },
    {
      end: 957.6,
      speaker: 'John Guthrie, Executive Vice President and Chief Financial Officer.',
      start: 947.88,
      text: 'As Doug mentioned, we have seen a sales pick up in April with drier conditions in the west and the start of spring in the north.',
    },
    {
      end: 978.56,
      speaker: 'John Guthrie, Executive Vice President and Chief Financial Officer.',
      start: 957.6,
      text: 'Organic daily sales for landscaping products, which includes irrigation, nursery, hardscapes, outdoor lighting, and landscape accessories grew 1% for the first quarter as price inflation and strong sales in southern markets more than offset the reduced volume resulting from the unfavorable weather and moderating economic conditions.',
    },
    {
      end: 994.3199999999999,
      speaker: 'John Guthrie, Executive Vice President and Chief Financial Officer.',
      start: 978.56,
      text: 'Organic daily sales growth for agronomic products, which includes fertilizer, control products, ice milk, and equipment, decreased 9% for the quarter due to the slow start to spring, moderating economic conditions, and reduced sales of ice milk products.',
    },
    {
      end: 998.28,
      speaker: 'John Guthrie, Executive Vice President and Chief Financial Officer.',
      start: 994.3199999999999,
      text: 'We are pleased with the performance of our acquisitions in the first quarter.',
    },
    {
      end: 1012.1999999999999,
      speaker: 'John Guthrie, Executive Vice President and Chief Financial Officer.',
      start: 998.28,
      text: 'Acquisition sales, which replete the sales attributable to acquisitions completed in both 2022 and 2023, contributed approximately $57 million or 7% to net sales growth.',
    },
    {
      end: 1017.84,
      speaker: 'John Guthrie, Executive Vice President and Chief Financial Officer.',
      start: 1012.1999999999999,
      text: 'Scott will provide more details regarding our acquisition strategy later in the call.',
    },
    {
      end: 1026.3600000000001,
      speaker: 'John Guthrie, Executive Vice President and Chief Financial Officer.',
      start: 1017.84,
      text: 'Growth profit increased 7% to $287 million for the first quarter compared to $269 million for the prior year period.',
    },
    {
      end: 1042.04,
      speaker: 'John Guthrie, Executive Vice President and Chief Financial Officer.',
      start: 1026.3600000000001,
      text: 'Growth margin increased 90 basis points to 34.3% as lower freight costs and contributions from acquisitions with higher gross margins offset the absence of the large price realization benefit we realized in the first quarter of 2022.',
    },
    {
      end: 1053.0800000000002,
      speaker: 'John Guthrie, Executive Vice President and Chief Financial Officer.',
      start: 1042.04,
      text: 'The gross margin benefit from acquisitions was over 100 basis points this quarter as many of our recent acquisitions specialize in higher gross margin products like mulch and bulk landscape supplies.',
    },
    {
      end: 1060.0800000000002,
      speaker: 'John Guthrie, Executive Vice President and Chief Financial Officer.',
      start: 1053.0800000000002,
      text: 'However, these products also carry more SG&A due to increased handling and transportation costs.',
    },
    {
      end: 1070.4,
      speaker: 'John Guthrie, Executive Vice President and Chief Financial Officer.',
      start: 1060.0800000000002,
      text: 'As expected, gross margin for our base business was down this quarter as the large price realization benefit in the first quarter of last year was not realized again.',
    },
    {
      end: 1079.48,
      speaker: 'John Guthrie, Executive Vice President and Chief Financial Officer.',
      start: 1070.4,
      text: 'Selling, general, and administrative expense for SG&A increased 26% to $291 million for the first quarter.',
    },
    {
      end: 1090.0800000000002,
      speaker: 'John Guthrie, Executive Vice President and Chief Financial Officer.',
      start: 1079.48,
      text: 'The increase in SG&A reflects the impact of acquisitions, cost inflation, and incremental investments in operating expenses to support our growth.',
    },
    {
      end: 1094,
      speaker: 'John Guthrie, Executive Vice President and Chief Financial Officer.',
      start: 1090.0800000000002,
      text: 'Acquisitions accounted for over half of the increase in SG&A this quarter.',
    },
    {
      end: 1102.56,
      speaker: 'John Guthrie, Executive Vice President and Chief Financial Officer.',
      start: 1094,
      text: 'SG&A as a percentage of net sales increased 620 basis points in the quarter to 34.8%.',
    },
    {
      end: 1113.28,
      speaker: 'John Guthrie, Executive Vice President and Chief Financial Officer.',
      start: 1102.56,
      text: 'The increase in SG&A as a percentage of net sales primarily reflects increased SG&A investment combined with the low sales in the seasonally slow first quarter.',
    },
    {
      end: 1124.36,
      speaker: 'John Guthrie, Executive Vice President and Chief Financial Officer.',
      start: 1113.28,
      text: 'For the first quarter, we recorded an income tax benefit of $2.7 million compared to income tax expense of $4.6 million in the prior year period.',
    },
    {
      end: 1132.8,
      speaker: 'John Guthrie, Executive Vice President and Chief Financial Officer.',
      start: 1124.36,
      text: 'The effective tax rate was 37.5% for the first quarter of 2023 compared to 12.5% for the prior year period.',
    },
    {
      end: 1146.24,
      speaker: 'John Guthrie, Executive Vice President and Chief Financial Officer.',
      start: 1132.8,
      text: 'The change in the effective tax rate was primarily due to a decrease in net income before taxes, to a net loss before taxes, and a decrease in the amount of excess tax benefits from stock-based compensations.',
    },
    {
      end: 1151.96,
      speaker: 'John Guthrie, Executive Vice President and Chief Financial Officer.',
      start: 1146.24,
      text: 'Excess tax benefits of $0.8 million were recognized for the first quarter of 2023 compared to',
    },
    {
      end: 1166.8,
      speaker: 'John Guthrie, Executive Vice President and Chief Financial Officer',
      start: 1151.96,
      text: '$5 million for the prior year period. We expect the 2023 fiscal year effective tax rate will be between 25% and 26%, excluding discrete items such as excess tax benefits.',
    },
    {
      end: 1174.64,
      speaker: 'John Guthrie, Executive Vice President and Chief Financial Officer.',
      start: 1166.8,
      text: 'We recorded a net loss of $4.5 million for the first quarter of 2023 compared to net income of $32.3 million for the prior year period.',
    },
    {
      end: 1181.5600000000002,
      speaker: 'John Guthrie, Executive Vice President and Chief Financial Officer.',
      start: 1174.64,
      text: 'As higher net sales and gross margins were offset by the increased net GNA expense.',
    },
    {
      end: 1187.72,
      speaker: 'John Guthrie, Executive Vice President and Chief Financial Officer.',
      start: 1181.5600000000002,
      text: 'Our weighted average diluted share account was $45 million compared to $45.9 million for the prior year period.',
    },
    {
      end: 1199.28,
      speaker: 'John Guthrie, Executive Vice President and Chief Financial Officer.',
      start: 1187.72,
      text: 'The shares used in the calculation of diluted EPS this quarter do not give effect to any diluted securities as the inclusion would decrease the net loss per common share.',
    },
    {
      end: 1210.12,
      speaker: 'John Guthrie, Executive Vice President and Chief Financial Officer.',
      start: 1199.28,
      text: 'Adjusted EBITDA decreased by 41% to $39.8 million for the first quarter compared to $67.8 million for the same period in the prior year.',
    },
    {
      end: 1216.04,
      speaker: 'John Guthrie, Executive Vice President and Chief Financial Officer.',
      start: 1210.12,
      text: 'Adjusted EBITDA margin decreased 360 basis points to 4.8%.',
    },
    {
      end: 1223.32,
      speaker: 'John Guthrie, Executive Vice President and Chief Financial Officer.',
      start: 1216.04,
      text: 'Now I would like to provide a brief update on our balance sheet and cash flow statement as shown on slide 10.',
    },
    {
      end: 1231.72,
      speaker: 'John Guthrie, Executive Vice President and Chief Financial Officer.',
      start: 1223.32,
      text: 'Networking capital at the end of the first quarter was $960 million compared to $788 million at the end of the prior year period.',
    },
    {
      end: 1243.52,
      speaker: 'John Guthrie, Executive Vice President and Chief Financial Officer.',
      start: 1231.72,
      text: 'The increase in networking capital is primarily attributable to our seasonal build-in inventory in preparation for the spring selling season, new acquisitions, and the impact of inflation.',
    },
    {
      end: 1253.6799999999998,
      speaker: 'John Guthrie, Executive Vice President and Chief Financial Officer.',
      start: 1243.52,
      text: 'Cash used in operations increased to approximately $153 million in the first quarter compared to approximately $118 million in the prior year period.',
    },
    {
      end: 1263.52,
      speaker: 'John Guthrie, Executive Vice President and Chief Financial Officer.',
      start: 1253.6799999999998,
      text: 'The increase in cash used in operations was primarily due to our decline in net income and a higher seasonal investment in working capital.',
    },
    {
      end: 1272.28,
      speaker: 'John Guthrie, Executive Vice President and Chief Financial Officer.',
      start: 1263.52,
      text: 'We made cash investment of approximately $40 million for the first quarter compared to approximately $41 million for the same quarter of 2022.',
    },
    {
      end: 1281.96,
      speaker: 'John Guthrie, Executive Vice President and Chief Financial Officer.',
      start: 1272.28,
      text: 'The decrease reflects a small decline in acquisition investment in the first three months of 2023 compared to the same period of 2022.',
    },
    {
      end: 1292.16,
      speaker: 'John Guthrie, Executive Vice President and Chief Financial Officer.',
      start: 1281.96,
      text: 'Net debt at the end of the quarter was approximately $586 million compared to approximately $417 million at the end of the first quarter of 2022.',
    },
    {
      end: 1301.76,
      speaker: 'John Guthrie, Executive Vice President and Chief Financial Officer.',
      start: 1292.16,
      text: 'Leverage increased to 1.3 times our trailing 12-month adjusted EBITDA compared to 0.9 times at the end of the first quarter last year.',
    },
    {
      end: 1309.52,
      speaker: 'John Guthrie, Executive Vice President and Chief Financial Officer.',
      start: 1301.76,
      text: 'The higher leverage primarily reflects increased borrowings to fund our investment in acquisitions and increased working capital.',
    },
    {
      end: 1316.72,
      speaker: 'John Guthrie, Executive Vice President and Chief Financial Officer.',
      start: 1309.52,
      text: 'As a reminder, our target year-end net debt to adjusted EBITDA leverage range is one to two times.',
    },
    {
      end: 1332.12,
      speaker: 'John Guthrie, Executive Vice President and Chief Financial Officer.',
      start: 1316.72,
      text: 'At the end of the quarter, we had available liquidity of approximately $330 million, which consisted of approximately $40 million of cash on hand and approximately $273 million in available capacity under our ABL facility.',
    },
    {
      end: 1337.2,
      speaker: 'John Guthrie, Executive Vice President and Chief Financial Officer.',
      start: 1332.12,
      text: 'I will now turn the call over to Scott for an update on our acquisition strategy.',
    },
    {
      end: 1338.2,
      speaker: 'Scott Salmon, Executive Vice President ',
      start: 1337.2,
      text: 'Thanks, John.',
    },
    {
      end: 1345.48,
      speaker: 'Scott Salmon, Executive Vice President ',
      start: 1338.2,
      text: 'As shown on slide 11, we acquired two companies in the first quarter with a combined trailing 12-month net sales of approximately $40 million.',
    },
    {
      end: 1354.6000000000001,
      speaker: 'Scott Salmon, Executive Vice President ',
      start: 1345.48,
      text: 'Since 2014, we have acquired 82 companies with approximately $1.5 billion in trailing 12-month net sales added to Site 1.',
    },
    {
      end: 1360.76,
      speaker: 'Scott Salmon, Executive Vice President ',
      start: 1354.6000000000001,
      text: 'Turning to slides 12 and 13, you will find information on our most recent acquisitions.',
    },
    {
      end: 1371.6,
      speaker: 'Scott Salmon, Executive Vice President ',
      start: 1360.76,
      text: 'On March 14, we acquired J&J Materials with five locations focused on providing hardscapes and bulk landscape supplies to the Rhode Island and Southeastern Massachusetts markets.',
    },
    {
      end: 1377.4799999999998,
      speaker: 'Scott Salmon, Executive Vice President ',
      start: 1371.6,
      text: 'This acquisition complements our prior acquisition of another regional hardscape leader, Kate Codstone.',
    },
    {
      end: 1389.4399999999998,
      speaker: 'Scott Salmon, Executive Vice President ',
      start: 1377.4799999999998,
      text: 'On March 28, we acquired Triangle Landscape Supplies with four locations providing bulk landscape supplies and hardscapes to landscape contractors in the Raleigh-Durham market.',
    },
    {
      end: 1400.08,
      speaker: 'Scott Salmon, Executive Vice President ',
      start: 1389.4399999999998,
      text: 'These acquisitions add terrific talent to Site 1 and move us forward toward our goal of providing a full line of landscape products and services to our customers in all major U.S. and Canadian markets.',
    },
    {
      end: 1405.76,
      speaker: 'Scott Salmon, Executive Vice President ',
      start: 1400.08,
      text: 'Summarizing on slide 14, our acquisition strategy continues to create significant value for',
    },
    {
      end: 1416.76,
      speaker: 'John Guthrie, Executive Vice President and Chief Financial Officer',
      start: 1405.76,
      text: 'Site 1. With a strong balance sheet and a robust pipeline across all lines of business and geographies, we are confident that we will be able to add many more outstanding companies to Site 1 during the year.',
    },
    {
      end: 1426.3600000000001,
      speaker: 'Scott Salmon, Executive Vice President ',
      start: 1416.76,
      text: 'I want to thank the entire Site 1 team for their passion and commitment to making Site 1 a great place to work and for welcoming the newly acquired teams when they joined the Site 1 family.',
    },
    {
      end: 1436.4,
      speaker: 'Scott Salmon, Executive Vice President ',
      start: 1426.3600000000001,
      text: 'I am confident in our ability to keep adding more outstanding companies through acquisition as we move through 2023, creating terrific value for all of our stakeholders.',
    },
    {
      end: 1438.72,
      speaker: 'Scott Salmon, Executive Vice President ',
      start: 1436.4,
      text: 'I will now turn the call back to Doug.',
    },
    {
      end: 1440.2,
      speaker: 'Doug Black, CEO',
      start: 1438.72,
      text: 'Thanks, Scott.',
    },
    {
      end: 1444.64,
      speaker: 'Doug Black, CEO',
      start: 1440.2,
      text: "I'll wrap up on slide 15.",
    },
    {
      end: 1451.36,
      speaker: 'Doug Black, CEO',
      start: 1444.64,
      text: 'Our outlook for 2023 remains largely the same as it was during our last earnings call in February.',
    },
    {
      end: 1463.36,
      speaker: 'Doug Black, CEO',
      start: 1451.36,
      text: 'As John mentioned, routine inflation continued to moderate, and we expect that to continue with flat prices in the second half, yielding low single-digit inflation for the full year.',
    },
    {
      end: 1472.32,
      speaker: 'Doug Black, CEO',
      start: 1463.36,
      text: 'In terms of end markets, we continue to expect a decline in new residential construction, which comprises 21 percent of our sales.',
    },
    {
      end: 1481.3600000000001,
      speaker: 'Doug Black, CEO',
      start: 1472.32,
      text: 'That is offset by flat to modest growth in the more resilient maintenance, repair and upgrade and new commercial construction end markets.',
    },
    {
      end: 1490.1200000000001,
      speaker: 'Doug Black, CEO',
      start: 1481.3600000000001,
      text: 'Note that we have not yet seen any negative effects on commercial construction driven by the recent banking crisis.',
    },
    {
      end: 1499.88,
      speaker: 'Doug Black, CEO',
      start: 1490.1200000000001,
      text: 'Good backlogs and healthy bidding, we believe this market represents 14 percent of our sales, could grow slightly versus the prior year.',
    },
    {
      end: 1517.8400000000001,
      speaker: 'Doug Black, CEO',
      start: 1499.88,
      text: 'In total, we expect industry sales to decline in 2023, and with our ability to gain market share, we would continue to expect our organic daily sales to be flat to down mid-single digits, with modest price inflation being offset by reduced volume.',
    },
    {
      end: 1532.44,
      speaker: 'Doug Black, CEO',
      start: 1517.8400000000001,
      text: 'We expect our gross margin to normalize this year without the substantial benefit that we saw from strategic inventory purchases ahead of rapid inflation in 2021 and 2022.',
    },
    {
      end: 1540.8,
      speaker: 'Doug Black, CEO',
      start: 1532.44,
      text: 'Additionally, with flat to declining sales, we expect SG&A as a percentage of sales for our base business to increase modestly.',
    },
    {
      end: 1547.92,
      speaker: 'Doug Black, CEO',
      start: 1540.8,
      text: 'We expect acquisitions to benefit gross margin, but also increase SG&A as a percent of net sales.',
    },
    {
      end: 1562.44,
      speaker: 'Doug Black, CEO',
      start: 1547.92,
      text: 'Decreasing gross margin and increased SG&A as a percent of net sales, we expect adjusted EVDA margin to normalize in 2023, providing the foundation for further improvement over the longer term.',
    },
    {
      end: 1574.8,
      speaker: 'Doug Black, CEO',
      start: 1562.44,
      text: 'In terms of acquisitions, as Scott mentioned, we have a strong pipeline of high-quality companies and look forward to adding more of these to the Tsaiwan family in 2023.',
    },
    {
      end: 1581.1200000000001,
      speaker: 'Doug Black, CEO',
      start: 1574.8,
      text: 'Our acquisitions are performing well, and we continue to improve our ability to integrate them into our company.',
    },
    {
      end: 1587.84,
      speaker: 'Doug Black, CEO',
      start: 1581.1200000000001,
      text: 'Importantly, we expect acquisitions to contribute strongly to our performance and growth during the year.',
    },
    {
      end: 1604.32,
      speaker: 'Doug Black, CEO',
      start: 1587.84,
      text: 'With all these factors in mind, we are maintaining our full-year guidance and anticipate our fiscal 2023 adjusted EVDA to be in the range of $395 million to $425 million.',
    },
    {
      end: 1608.24,
      speaker: 'Doug Black, CEO',
      start: 1604.32,
      text: 'This range does not factor any contribution from unannounced acquisition.',
    },
    {
      end: 1618.88,
      speaker: 'Doug Black, CEO',
      start: 1608.24,
      text: 'In closing, I would like to sincerely thank all our Tsaiwan associates who continue to amaze me with their passion, commitment, teamwork, and selfless service.',
    },
    {
      end: 1625.52,
      speaker: 'Doug Black, CEO',
      start: 1618.88,
      text: "We have a tremendous team, and it's an honor to be joined with them as we deliver increasing value for all our stakeholders.",
    },
    {
      end: 1633.6000000000001,
      speaker: 'Doug Black, CEO',
      start: 1625.52,
      text: 'I would also like to thank our suppliers for supporting us so strongly and our customers for allowing us to be their partner.',
    },
    {
      end: 1636.88,
      speaker: 'Doug Black, CEO',
      start: 1633.6000000000001,
      text: 'Operator, please open the line for questions.',
    },
    {
      end: 1638.88,
      speaker: 'John Guthrie, Executive Vice President and Chief Financial Officer',
      start: 1636.88,
      text: 'Thank you.',
    },
    {
      end: 1645.2800000000002,
      speaker: 'Operator ',
      start: 1638.88,
      text: 'We will now be conducting a question and answer session.',
    },
    {
      end: 1651.64,
      speaker: 'Operator ',
      start: 1645.2800000000002,
      text: 'If you would like to ask a question, please press star 1 on your telephone keypad.',
    },
    {
      end: 1657.16,
      speaker: 'Operator ',
      start: 1651.64,
      text: 'A confirmation tone will indicate that your line is in the question queue.',
    },
    {
      end: 1662.2800000000002,
      speaker: 'Operator ',
      start: 1657.16,
      text: 'You may press star 2 if you would like to remove your question from the queue.',
    },
    {
      end: 1670.3600000000001,
      speaker: 'Operator ',
      start: 1662.2800000000002,
      text: 'For participants using speaker equipment, it may be necessary to pick up your headset before pressing the star key.',
    },
    {
      end: 1676.1200000000001,
      speaker: 'Operator ',
      start: 1670.3600000000001,
      text: 'Please link yourself to one main question and one follow-up.',
    },
    {
      end: 1682,
      speaker: 'Operator ',
      start: 1676.1200000000001,
      text: 'One moment please while we pull for questions.',
    },
    {
      end: 1687,
      speaker: 'Operator ',
      start: 1682,
      text: 'And our first question comes from David Mende with Birthday.',
    },
    {
      end: 1690.2,
      speaker: 'David Mende, Birthday',
      start: 1687,
      text: 'Yes, thank you.',
    },
    {
      end: 1692.92,
      speaker: 'David Mende, Birthday',
      start: 1690.2,
      text: 'First off, a clarifying question.',
    },
    {
      end: 1703.3200000000002,
      speaker: 'David Mende, Birthday',
      start: 1692.92,
      text: 'You said that average daily sales were down 2% in the first quarter, but then I think you said that year-to-date through April they were plus one.',
    },
    {
      end: 1705.3200000000002,
      speaker: 'David Mende, Birthday',
      start: 1703.3200000000002,
      text: 'I just want to be clear on that.',
    },
    {
      end: 1707.92,
      speaker: 'John Guthrie, Executive Vice President and Chief Financial Officer.',
      start: 1705.3200000000002,
      text: "Yes, that's correct.",
    },
    {
      end: 1715.28,
      speaker: 'David Mende, Birthday',
      start: 1707.92,
      text: "Okay, so I mean April sales volumes would be higher than January, February, and March, but that's still an encouraging sign.",
    },
    {
      end: 1729.16,
      speaker: 'David Mende, Birthday',
      start: 1715.28,
      text: 'I guess that leads to the question here that sometimes inclement weather leads to sales that are completely missed, and then other times these sales are just simply delayed, pushed to the right.',
    },
    {
      end: 1736.28,
      speaker: 'David Mende, Birthday',
      start: 1729.16,
      text: 'Could you characterize the first quarter weather-affected geographies and the nature of those sales?',
    },
    {
      end: 1740.04,
      speaker: 'Doug Black, CEO',
      start: 1736.28,
      text: "Yes, so you're correct.",
    },
    {
      end: 1743.56,
      speaker: 'Doug Black, CEO',
      start: 1740.04,
      text: 'The first and second quarter kind of split.',
    },
    {
      end: 1754.96,
      speaker: 'Doug Black, CEO',
      start: 1743.56,
      text: 'Spring starts at the end of the first quarter and rolls into the second, so often you can get more sales into the first or less and more into the second.',
    },
    {
      end: 1761.36,
      speaker: 'Doug Black, CEO',
      start: 1754.96,
      text: 'We would characterize the weather dynamic as mostly that.',
    },
    {
      end: 1782.04,
      speaker: 'Doug Black, CEO',
      start: 1761.36,
      text: "In our northern markets, for instance, where spring kind of came later than in 2022, we're seeing the robust sales come in, the fertilizer applications get done, and we don't think we missed anything, and as we mentioned, as a company in a whole, we've kind of largely made that up.",
    },
    {
      end: 1786.3200000000002,
      speaker: 'Doug Black, CEO',
      start: 1782.04,
      text: 'One area where we might not make it up is California in the west.',
    },
    {
      end: 1787.3200000000002,
      speaker: 'Doug Black, CEO',
      start: 1786.3200000000002,
      text: "It's been very wet.",
    },
    {
      end: 1807.8,
      speaker: 'Doug Black, CEO',
      start: 1787.3200000000002,
      text: "That's an all-weather market, and so there's been several months of just really record rainfall, and we probably won't make all of that back up, but in the scheme of things, the weather has moved sales around, but we think it's still all to play for this year.",
    },
    {
      end: 1808.8,
      speaker: 'David Mende, Birthday',
      start: 1807.8,
      text: 'Okay.',
    },
    {
      end: 1809.8,
      speaker: 'David Mende, Birthday',
      start: 1808.8,
      text: "That's helpful.",
    },
    {
      end: 1810.8,
      speaker: 'David Mende, Birthday',
      start: 1809.8,
      text: 'Thank you.',
    },
    {
      end: 1817.8,
      speaker: 'David Mende, Birthday',
      start: 1810.8,
      text: 'Second, on the gross margin guidance, back in February of this year, you said 34 to 34 and a half.',
    },
    {
      end: 1820.24,
      speaker: 'David Mende, Birthday',
      start: 1817.8,
      text: "Now you're saying higher than previously thought.",
    },
    {
      end: 1826.52,
      speaker: 'David Mende, Birthday',
      start: 1820.24,
      text: "Given that you're not changing your EBITDA guidance, I guess that naturally assumes higher SG&A.",
    },
    {
      end: 1832.52,
      speaker: 'David Mende, Birthday',
      start: 1826.52,
      text: 'Could you talk about the sources of upside to operating expenses?',
    },
    {
      end: 1833.52,
      speaker: 'John Guthrie, Executive Vice President and Chief Financial Officer.',
      start: 1832.52,
      text: 'Yeah.',
    },
    {
      end: 1844.8,
      speaker: 'John Guthrie, Executive Vice President and Chief Financial Officer.',
      start: 1833.52,
      text: "With regards to SG&A and just SG&A in general, I think what we've seen is kind of the roll in of these acquisitions that have higher SG&A.",
    },
    {
      end: 1849.28,
      speaker: 'John Guthrie, Executive Vice President and Chief Financial Officer.',
      start: 1844.8,
      text: "That's one kind of a mixed issue that's driving our SG&A.",
    },
    {
      end: 1879.72,
      speaker: 'John Guthrie, Executive Vice President and Chief Financial Officer.',
      start: 1849.28,
      text: "I think also, if you look at year over year, the increase in Q1 is especially accentuated as a percentage of sales, obviously, because of the low sales volume, but also most of the hiring that we're seeing in the comp was really done last spring in 2022, so as we start comping year over year, the difference goes down.",
    },
    {
      end: 1902.28,
      speaker: 'John Guthrie, Executive Vice President and Chief Financial Officer.',
      start: 1879.72,
      text: "We've also taken, in certain markets, we've already taken actions to address some of the challenges that we're having with sales, and then also I would say in general, we're not doing any hiring, even much hiring across the board at all, given the uncertainty in the marketplace.",
    },
    {
      end: 1914.48,
      speaker: 'John Guthrie, Executive Vice President and Chief Financial Officer.',
      start: 1902.28,
      text: "So certainly, areas where we can take actions, I'm pleased with the sales growth that we're seeing in April, but monitoring it closely.",
    },
    {
      end: 1915.48,
      speaker: 'John Guthrie, Executive Vice President and Chief Financial Officer',
      start: 1914.48,
      text: 'Okay.',
    },
    {
      end: 1919,
      speaker: 'David Mende, Birthday',
      start: 1915.48,
      text: 'Thanks very much.',
    },
    {
      end: 1922,
      speaker: 'David Mende, Birthday',
      start: 1919,
      text: 'Thank you.',
    },
    {
      end: 1926.88,
      speaker: 'Operator ',
      start: 1922,
      text: 'Our next question comes from Ryan Marco with William Blair.',
    },
    {
      end: 1933.2800000000002,
      speaker: 'Ryan Marco, William Blair',
      start: 1926.88,
      text: 'Hey, guys, two questions from me, one on sales and then one on gross margin.',
    },
    {
      end: 1953,
      speaker: 'Ryan Marco, William Blair',
      start: 1933.2800000000002,
      text: "So first on sales, can you just tell us what April organic growth was, and then I'm curious, when you talk to contractors, the resi contractors, what are they telling you in terms of backlog and bookings, because it feels to me like things are tracking pretty well, and maybe there's a bit of upside to guidance for sales.",
    },
    {
      end: 1965.12,
      speaker: 'Doug Black, CEO',
      start: 1953,
      text: "Yeah, so in April, we're kind of in high single digits in terms of sales in April, so we're pleased with that.",
    },
    {
      end: 2012.28,
      speaker: 'Doug Black, CEO',
      start: 1965.12,
      text: "In terms of the builders, we're still calling the market to be down, but we would agree that the builders, they seem to be a bit more confident than they say it would have been three to six months ago, and we'll see how it plays out, but it seems like that market could be a little more resilient than we thought it was going to be, and the builders, they're still, again, we're still calling that market down, but let's say net net, there probably is a little more confidence than, again, we would have seen or we would have heard from them three to six months ago.",
    },
    {
      end: 2019.56,
      speaker: 'Ryan Marco, William Blair',
      start: 2012.28,
      text: 'And as it relates to the maintenance part of the business for resi, I think last year you said inflation was sort of impacting budgets a bit.',
    },
    {
      end: 2024.04,
      speaker: 'Ryan Marco, William Blair',
      start: 2019.56,
      text: 'Have you seen that sort of normalized?',
    },
    {
      end: 2030.84,
      speaker: 'John Guthrie, Executive Vice President and Chief Financial Officer.',
      start: 2024.04,
      text: "I wouldn't say we've really seen that yet.",
    },
    {
      end: 2034.88,
      speaker: 'John Guthrie, Executive Vice President and Chief Financial Officer.',
      start: 2030.84,
      text: "We are seeing, obviously, that's been one of the growth areas here in April.",
    },
    {
      end: 2057.2400000000002,
      speaker: 'John Guthrie, Executive Vice President and Chief Financial Officer.',
      start: 2034.88,
      text: "The weather played a major role in Q1 with regards to kind of our agronomic sales, monitoring it closely, and we have seen, obviously, a recovery in April, but whether year over year we're going to be up or down, I'm watching that right now.",
    },
    {
      end: 2058.7200000000003,
      speaker: 'Ryan Marco, William Blair',
      start: 2057.2400000000002,
      text: 'Got it.',
    },
    {
      end: 2059.7200000000003,
      speaker: 'Ryan Marco, William Blair',
      start: 2058.7200000000003,
      text: 'Okay.',
    },
    {
      end: 2063.32,
      speaker: 'Ryan Marco, William Blair',
      start: 2059.7200000000003,
      text: 'And then on gross margins, can you just unpack the freight upside?',
    },
    {
      end: 2068.28,
      speaker: 'Ryan Marco, William Blair',
      start: 2063.32,
      text: "Is that lower fuel, is it supply chains normalizing so that's helping costs?",
    },
    {
      end: 2078.2400000000002,
      speaker: 'Ryan Marco, William Blair',
      start: 2068.28,
      text: 'And then how much do you think freight will end up helping you for the year relative to what you saw three months ago?',
    },
    {
      end: 2080.84,
      speaker: 'John Guthrie, Executive Vice President and Chief Financial Officer.',
      start: 2078.2400000000002,
      text: "So in general, it's a combination of both.",
    },
    {
      end: 2084.8,
      speaker: 'John Guthrie, Executive Vice President and Chief Financial Officer.',
      start: 2080.84,
      text: "I think we're managing our freight better from that standpoint.",
    },
    {
      end: 2092.72,
      speaker: 'John Guthrie, Executive Vice President and Chief Financial Officer.',
      start: 2084.8,
      text: 'It is, when we talk about this, it is primarily inbound freight from that perspective.',
    },
    {
      end: 2107.2799999999997,
      speaker: 'John Guthrie, Executive Vice President and Chief Financial Officer.',
      start: 2092.72,
      text: 'Year to date, in Q1, it was approximately a 40 basis point positive pickup year over year in our Q1 results.',
    },
    {
      end: 2116.28,
      speaker: 'John Guthrie, Executive Vice President and Chief Financial Officer.',
      start: 2107.2799999999997,
      text: "We're optimistic that going into the year without being that freight will be a positive.",
    },
    {
      end: 2125.44,
      speaker: 'John Guthrie, Executive Vice President and Chief Financial Officer.',
      start: 2116.28,
      text: 'We had some of that built into kind of our existing numbers, but we would expect for the full year.',
    },
    {
      end: 2131.92,
      speaker: 'John Guthrie, Executive Vice President and Chief Financial Officer.',
      start: 2125.44,
      text: 'I think the market has even gotten better since we gave original guidance.',
    },
    {
      end: 2132.92,
      speaker: 'Ryan Marco, William Blair',
      start: 2131.92,
      text: 'Got it.',
    },
    {
      end: 2133.92,
      speaker: 'Ryan Marco, William Blair',
      start: 2132.92,
      text: 'Helpful.',
    },
    {
      end: 2134.92,
      speaker: 'John Guthrie, Executive Vice President and Chief Financial Officer',
      start: 2133.92,
      text: 'Thank you.',
    },
    {
      end: 2141.48,
      speaker: 'Operator ',
      start: 2134.92,
      text: 'Our next question comes from Mattel Bowley with Barclays.',
    },
    {
      end: 2180.92,
      speaker: 'Mattel Bowley, Barclays',
      start: 2141.48,
      text: "Hey. Good morning, guys. Thanks for taking the question. Just on the gross margin, again, I guess we want a clarifying point. I think you said that acquisitions contributed 100 basis points to the gross margin in the quarter. I'm just curious if you could unpack that a little bit. I think you had something like $55 million to $60 million of acquired sales, so it seems like a big margin would be applied to those. More broadly, if you could just kind of step back and kind of update us on where you expect gross margin to settle out for the full year. Thank you.",
    },
    {
      end: 2181.92,
      speaker: 'John Guthrie, Executive Vice President and Chief Financial Officer',
      start: 2180.92,
      text: 'Yeah.',
    },
    {
      end: 2190.84,
      speaker: 'John Guthrie, Executive Vice President and Chief Financial Officer.',
      start: 2181.92,
      text: "What we're seeing with regards to some of the acquisitions, it's really kind of a product mix issue.",
    },
    {
      end: 2202.68,
      speaker: 'John Guthrie, Executive Vice President and Chief Financial Officer.',
      start: 2190.84,
      text: 'These acquisitions say, for instance, bring in higher gross margins and higher SG&A, I would think, on an adjusted EBITDA basis.',
    },
    {
      end: 2230.76,
      speaker: 'John Guthrie, Executive Vice President and Chief Financial Officer.',
      start: 2202.68,
      text: "Not too much of an issue, but for certain products, like multiple existence, relatively low cost, so the cost of handling and transportation is very high, thinking about the SG&A, but the actually product margin is relatively high, which is driving what we're seeing here.",
    },
    {
      end: 2261.4,
      speaker: 'John Guthrie, Executive Vice President and Chief Financial Officer.',
      start: 2230.76,
      text: "With regards to for the full year, we previously talked 34 to 34 and a half, we're probably 34 and a half to 35 now, would probably be a better full year number, as was previously pointed out, our EBITDA margin, our guidance hasn't really changed, so there may be some slightly higher SG&A coming along with that.",
    },
    {
      end: 2309.2400000000002,
      speaker: 'Mattel Bowley,  Barclays',
      start: 2261.4,
      text: "Got it. Okay. Thank you for that. Then, so I guess on that point, following to the SG&A side, so it sounds like you're kind of shifting 50 basis points towards gross margin and away from SG&A. I think on a dollar basis, SG&A was up something like $60 million in the quarter, you said acquisitions were more than half of that, how should we think about kind of the dollar spend on SG&A as we run through the year, is that kind of $60 million per quarter the right run rate, or presumably you're expecting that to decelerate meaningfully, so a little more color on what you're doing to kind of decelerate that SG&A spending increase. Thank you.",
    },
    {
      end: 2310.2400000000002,
      speaker: 'John Guthrie, Executive Vice President and Chief Financial Officer.',
      start: 2309.2400000000002,
      text: 'Yeah.',
    },
    {
      end: 2343.88,
      speaker: 'John Guthrie, Executive Vice President and Chief Financial Officer.',
      start: 2310.2400000000002,
      text: 'So the ink, and all this is predicated on us not, the future acquisitions that will obviously contribute to this, but all things considered, we would expect that $60 million as we start to come on some of the acquisitions we did last year, that that would probably be potentially 50% of the increase for the full year, and that would go down quarter by quarter with regards to it.',
    },
    {
      end: 2372.2400000000002,
      speaker: 'John Guthrie, Executive Vice President and Chief Financial Officer.',
      start: 2343.88,
      text: "Sequentially, we always, Q2 is always higher than Q1, but Q2, Q3, and Q4 historically have been relatively flat with regards to SG&A from a historical basis, and we're forecasting a similar number, relatively flat after this quarter.",
    },
    {
      end: 2381.04,
      speaker: 'Doug Black, CEO',
      start: 2372.2400000000002,
      text: "And John, when we're talking about acquisitions, we're talking about acquisitions that were completed in 2022 and through 2023, right?",
    },
    {
      end: 2382.04,
      speaker: 'John Guthrie, Executive Vice President and Chief Financial Officer',
      start: 2381.04,
      text: 'Right.',
    },
    {
      end: 2389.36,
      speaker: 'John Guthrie, Executive Vice President and Chief Financial Officer',
      start: 2382.04,
      text: "So you've got the whole set there, which brings that higher SG&A into the company.",
    },
    {
      end: 2391.72,
      speaker: 'John Guthrie, Executive Vice President and Chief Financial Officer',
      start: 2389.36,
      text: 'All right.',
    },
    {
      end: 2392.72,
      speaker: 'John Guthrie, Executive Vice President and Chief Financial Officer',
      start: 2391.72,
      text: 'Thanks Doug.',
    },
    {
      end: 2393.72,
      speaker: 'John Guthrie, Executive Vice President and Chief Financial Officer',
      start: 2392.72,
      text: 'Thanks John.',
    },
    {
      end: 2410.8,
      speaker: 'Operator ',
      start: 2393.72,
      text: 'Excuse me, ladies and gentlemen, please remind to limit to one main question and one follow-up.',
    },
    {
      end: 2412.32,
      speaker: 'Operator ',
      start: 2410.8,
      text: 'Thank you.',
    },
    {
      end: 2418.2000000000003,
      speaker: 'Operator ',
      start: 2412.32,
      text: 'And our first question comes from Mike Dow with RBC Capital Markets.',
    },
    {
      end: 2422.8,
      speaker: 'Chris Clawdon, RBC Capital Markets',
      start: 2418.2000000000003,
      text: 'Hi, this is actually Chris Clawdon from Mike.',
    },
    {
      end: 2425,
      speaker: 'Chris Clawdon, RBC Capital Markets',
      start: 2422.8,
      text: 'Thanks for taking our questions.',
    },
    {
      end: 2440.68,
      speaker: 'Chris Clawdon, RBC Capital Markets',
      start: 2425,
      text: 'Just moving over to the pricing side, how much of a headwind was lower PVC and fertilizer pricing for you this quarter, and how are you guys thinking about the magnitude of that headwind on the year-over-year basis evolving through the rest of the year?',
    },
    {
      end: 2444.2799999999997,
      speaker: 'John Guthrie, Executive Vice President and Chief Financial Officer.',
      start: 2440.68,
      text: 'Well, it will be a headwind for the rest of the year.',
    },
    {
      end: 2455.24,
      speaker: 'John Guthrie, Executive Vice President and Chief Financial Officer.',
      start: 2444.2799999999997,
      text: 'I mean, both of those items contributed were negative year-over-year in Q1, and March was a greater.',
    },
    {
      end: 2473.88,
      speaker: 'John Guthrie, Executive Vice President and Chief Financial Officer.',
      start: 2455.24,
      text: "There's still year-over-year on a percentage basis, there's still on a year-over-year basis, there's still, I would say, mid to low single digits down contribution.",
    },
    {
      end: 2483.92,
      speaker: 'John Guthrie, Executive Vice President and Chief Financial Officer.',
      start: 2473.88,
      text: 'So from that standpoint, but you know, I think if you look sequentially, it would be greater than that because prices rose throughout the year last year.',
    },
    {
      end: 2500.36,
      speaker: 'John Guthrie, Executive Vice President and Chief Financial Officer.',
      start: 2483.92,
      text: 'So, so far this year, negative growth, but you know, on a year-over-year basis in Q1, they were low to mid single digits down.',
    },
    {
      end: 2503.16,
      speaker: 'Chris Clawdon, RBC Capital Markets',
      start: 2500.36,
      text: 'Got it.',
    },
    {
      end: 2504.16,
      speaker: 'Chris Clawdon, RBC Capital Markets',
      start: 2503.16,
      text: 'Thanks for that.',
    },
    {
      end: 2525.88,
      speaker: 'Chris Clawdon, RBC Capital Markets',
      start: 2504.16,
      text: 'And just going back to the organic daily sales comments in April, how much of the high single digit growth was price versus volume, and is there a way to think about, you know, how much of the volume contribution of that high single digit was just kind of weather-delayed projects versus, you know, just non-weather-impacted?',
    },
    {
      end: 2534.32,
      speaker: 'Chris Clawdon, RBC Capital Markets',
      start: 2525.88,
      text: "And then just lastly on that, is 15% of sales still kind of a good number to use in terms of April's contribution to full year sales?",
    },
    {
      end: 2563.2,
      speaker: 'Doug Black, CEO',
      start: 2534.32,
      text: "Yeah, well, on the first question, I think the way to think about it is, you know, April has been, you know, built into that, you know, high single digit growth is some catch-up from the first quarter, so if you look at the 1% year-to-date, you know, that's probably a better number to index on, and, you know, there's some inflation on that balanced with, you know, net negative volume growth.",
    },
    {
      end: 2582.04,
      speaker: 'Doug Black, CEO',
      start: 2563.2,
      text: 'And so, you know, by nature, you know, the April number would be, you know, less inflation, more volume, to get to that 1%, which is, you know, a combination of the two.',
    },
    {
      end: 2585.04,
      speaker: 'Doug Black, CEO',
      start: 2582.04,
      text: 'And what was the second question?',
    },
    {
      end: 2599.32,
      speaker: 'Chris Clawdon, RBC Capital Markets',
      start: 2585.04,
      text: 'Yeah, just if I think in the past you said kind of April monthly contribution to full year sales is around 15%, is that still kind of a good number to use or has kind of affected that at all?',
    },
    {
      end: 2605.04,
      speaker: 'John Guthrie, Executive Vice President and Chief Financial Officer.',
      start: 2599.32,
      text: "Yeah, I would say it's probably 13% to 15%.",
    },
    {
      end: 2606.04,
      speaker: 'John Guthrie, Executive Vice President and Chief Financial Officer.',
      start: 2605.04,
      text: 'Okay.',
    },
    {
      end: 2613.04,
      speaker: 'Chris Clawdon, RBC Capital Markets',
      start: 2606.04,
      text: 'Appreciate it all, Clark.',
    },
    {
      end: 2620.0800000000004,
      speaker: 'Operator ',
      start: 2613.04,
      text: 'And our next question comes from Kate Hodis with Trust Securities.',
    },
    {
      end: 2621.0800000000004,
      speaker: 'Kate Hodis, Trust Securities',
      start: 2620.0800000000004,
      text: 'Thank you.',
    },
    {
      end: 2642.1600000000003,
      speaker: 'Kate Hodis, Trust Securities',
      start: 2621.0800000000004,
      text: "So we've talked a lot about SG&A in this call, and some of the statements I'm trying to hard to recognize, let me just ask it this way, is the percentage of sales under your guidance, what do you think SG&A will look like by the end of the year?",
    },
    {
      end: 2646.6,
      speaker: 'John Guthrie, Executive Vice President and Chief Financial Officer.',
      start: 2642.1600000000003,
      text: 'What do we think SG&A will look like?',
    },
    {
      end: 2647.6,
      speaker: 'John Guthrie, Executive Vice President and Chief Financial Officer.',
      start: 2646.6,
      text: 'Look like how?',
    },
    {
      end: 2648.6,
      speaker: 'John Guthrie, Executive Vice President and Chief Financial Officer.',
      start: 2647.6,
      text: 'Could you clarify that?',
    },
    {
      end: 2655.36,
      speaker: 'Kate Hodis, Trust Securities',
      start: 2648.6,
      text: "As a percentage of sales in the guidance range you've given, what roughly do you think we're looking at?",
    },
    {
      end: 2661.52,
      speaker: 'John Guthrie, Executive Vice President and Chief Financial Officer.',
      start: 2655.36,
      text: "Well, we're not going to specifically forecast out SG&A as a percentage sales.",
    },
    {
      end: 2669.44,
      speaker: 'John Guthrie, Executive Vice President and Chief Financial Officer.',
      start: 2661.52,
      text: 'I mean, we think it will de-lever, so it will be higher than previously.',
    },
    {
      end: 2675.76,
      speaker: 'John Guthrie, Executive Vice President and Chief Financial Officer.',
      start: 2669.44,
      text: 'I would kind of back into that number from our EBITDA packets.',
    },
    {
      end: 2676.76,
      speaker: 'Kate Hodis, Trust Securities',
      start: 2675.76,
      text: 'Okay.',
    },
    {
      end: 2682.52,
      speaker: 'Kate Hodis, Trust Securities',
      start: 2676.76,
      text: 'Let me switch over to the previous question about fertilizer.',
    },
    {
      end: 2688.88,
      speaker: 'Kate Hodis, Trust Securities',
      start: 2682.52,
      text: 'What are you hearing from suppliers in terms of, do we have a lot more deflation coming in?',
    },
    {
      end: 2689.88,
      speaker: 'Kate Hodis, Trust Securities',
      start: 2688.88,
      text: "We've already seen.",
    },
    {
      end: 2692.88,
      speaker: 'Kate Hodis, Trust Securities',
      start: 2689.88,
      text: "What's the market thinking on that?",
    },
    {
      end: 2698.36,
      speaker: 'John Guthrie, Executive Vice President and Chief Financial Officer.',
      start: 2692.88,
      text: "Well, we've seen a lot of deflation.",
    },
    {
      end: 2711.52,
      speaker: 'John Guthrie, Executive Vice President and Chief Financial Officer.',
      start: 2698.36,
      text: "I don't know if people are thinking that it will be additional, but obviously if you look at raw material prices right now, they're down significantly.",
    },
    {
      end: 2722.44,
      speaker: 'John Guthrie, Executive Vice President and Chief Financial Officer.',
      start: 2711.52,
      text: "I think they're even pre-COVID levels, so the fertilizer prices have come down a lot from that standpoint.",
    },
    {
      end: 2731.88,
      speaker: 'John Guthrie, Executive Vice President and Chief Financial Officer.',
      start: 2722.44,
      text: "I think kind of we feel as if kind of where they're at now is kind of where we would carry them forward, but we'll have to see.",
    },
    {
      end: 2735,
      speaker: 'John Guthrie, Executive Vice President and Chief Financial Officer.',
      start: 2731.88,
      text: "Obviously, that's a commodity and highly volatile.",
    },
    {
      end: 2736,
      speaker: 'John Guthrie, Executive Vice President and Chief Financial Officer',
      start: 2735,
      text: 'Okay.',
    },
    {
      end: 2737,
      speaker: 'Kate Hodis, Trust Securities',
      start: 2736,
      text: 'Thank you.',
    },
    {
      end: 2746.52,
      speaker: 'Operator ',
      start: 2737,
      text: 'Our next question comes from (inaudible) with Loop Capital Markets.',
    },
    {
      end: 2747.52,
      speaker: 'Questioner A, Loop Capital Markets',
      start: 2746.52,
      text: 'Hi.',
    },
    {
      end: 2750.16,
      speaker: 'Questioner A, Loop Capital Markets',
      start: 2747.52,
      text: 'Thanks for taking my questions today.',
    },
    {
      end: 2761.76,
      speaker: 'Questioner A, Loop Capital Markets',
      start: 2750.16,
      text: "At a high level, can you talk about the residential R&R bidding environment and what you've been hearing from professional customers about demand expectations through the back half of the year?",
    },
    {
      end: 2767.92,
      speaker: 'Doug Black, CEO',
      start: 2761.76,
      text: 'Our customers are busy.',
    },
    {
      end: 2783.48,
      speaker: 'Doug Black, CEO',
      start: 2767.92,
      text: 'We mentioned that the commercial market is holding up well as are the repair and remodel and maintenance markets, so our customers are busy.',
    },
    {
      end: 2791.56,
      speaker: 'Doug Black, CEO',
      start: 2783.48,
      text: "I'd say the extraordinary backlogs that we saw during COVID have normalized.",
    },
    {
      end: 2797.16,
      speaker: 'Doug Black, CEO',
      start: 2791.56,
      text: "I'd say NetNet customers are cautiously optimistic about the second half.",
    },
    {
      end: 2815.16,
      speaker: 'Doug Black, CEO',
      start: 2797.16,
      text: "They don't have the second half already loaded up in their backlogs, which they would have had in the last couple of years, but I'd say they're cautiously optimistic about what they're seeing in terms of bidding jobs today and what's coming down the pike.",
    },
    {
      end: 2835.72,
      speaker: 'Doug Black, CEO',
      start: 2815.16,
      text: 'We have a project services group that bids, we do put together bids for our customers in the commercial space, and that bidding has been that positive this year versus prior year, up a couple percent, so that gives us another kind of read into the commercial market.',
    },
    {
      end: 2841,
      speaker: 'Doug Black, CEO',
      start: 2835.72,
      text: 'The repair and remodel market is backlog driven.',
    },
    {
      end: 2854.68,
      speaker: 'Doug Black, CEO',
      start: 2841,
      text: "It's more you get the jobs as you go, so it's harder to get some visibility in the second half in that market, but in terms of commercial, we feel pretty good about how the year is developing. ",
    },
    {
      end: 2855.68,
      speaker: 'Questioner A, Loop Capital Markets',
      start: 2854.68,
      text: "Okay, great. That's helpful.",
    },
    {
      end: 2859.28,
      speaker: 'Questioner A, Loop Capital Markets',
      start: 2855.68,
      text: 'Then the M&A pipeline still sounds active.',
    },
    {
      end: 2864.52,
      speaker: 'Questioner A, Loop Capital Markets',
      start: 2859.28,
      text: 'Are you expecting a similar and organic growth contribution as this past year?',
    },
    {
      end: 2876.6,
      speaker: 'Scott Salmon, Executive Vice President ',
      start: 2864.52,
      text: "Well, obviously, it's impossible to predict that exactly, but last year at this time, we were sitting at three acquisitions and 50 million in trailing 12 months acquired this year.",
    },
    {
      end: 2877.6,
      speaker: 'Scott Salmon, Executive Vice President ',
      start: 2876.6,
      text: "We're at 2 in 40.",
    },
    {
      end: 2890.6,
      speaker: 'Scott Salmon, Executive Vice President ',
      start: 2877.6,
      text: 'Last year, we had a very strong pipeline, and this year, I would say our pipeline is as good or better, so we feel a good level of confidence that we can contribute a strong amount to overall for Site 1.',
    },
    {
      end: 2894.16,
      speaker: 'Scott Salmon, Executive Vice President ',
      start: 2890.6,
      text: "You can't predict it precisely, though.",
    },
    {
      end: 2895.16,
      speaker: 'Questioner A, Loop Capital Markets',
      start: 2894.16,
      text: 'Great.',
    },
    {
      end: 2896.16,
      speaker: 'John Guthrie, Executive Vice President and Chief Financial Officer',
      start: 2895.16,
      text: 'Thank you.',
    },
    {
      end: 2904.7999999999997,
      speaker: 'Operator ',
      start: 2896.16,
      text: 'Our next question comes from Joy (inaudible) with Deutsche Bank.',
    },
    {
      end: 2907.12,
      speaker: 'Joy,  Deutsche Bank',
      start: 2904.7999999999997,
      text: 'Yeah, good morning.',
    },
    {
      end: 2910.08,
      speaker: 'Joy,  Deutsche Bank',
      start: 2907.12,
      text: 'Thanks for taking my question.',
    },
    {
      end: 2911.08,
      speaker: 'Scott Salmon, Executive Vice President ',
      start: 2910.08,
      text: 'Morning.',
    },
    {
      end: 2927.44,
      speaker: 'Joy,  Deutsche Bank',
      start: 2911.08,
      text: "So, my first question is on the gross margin, and we've talked about it a bit, but if I'm thinking about it correctly, your expectations last quarter would have already assumed some of the mix from acquisitions, probably most of the mixed benefit year over year.",
    },
    {
      end: 2946.2400000000002,
      speaker: 'Joy,  Deutsche Bank',
      start: 2927.44,
      text: "And so, you were also expecting the inventory profits to roll off, and it seems like that probably happened in the quarter offset by the freight benefit, so is it right to think as we move from 1Q to 2Q to 3 and 4, you're not going to really see a sequential tick down in margins?",
    },
    {
      end: 2952.6,
      speaker: 'Joy,  Deutsche Bank',
      start: 2946.2400000000002,
      text: 'We should probably just be sort of steady through the remainder of the year to get to that full year expectation.',
    },
    {
      end: 2957.3599999999997,
      speaker: 'John Guthrie, Executive Vice President and Chief Financial Officer.',
      start: 2952.6,
      text: "I don't know if that's exactly the case.",
    },
    {
      end: 2975.64,
      speaker: 'John Guthrie, Executive Vice President and Chief Financial Officer.',
      start: 2957.3599999999997,
      text: "We're going to have a roll-off of the inventory profits in Q2 also from that standpoint, so that will be somewhat of a – that will be a headwind in Q2, as we've talked about.",
    },
    {
      end: 2991.04,
      speaker: 'John Guthrie, Executive Vice President and Chief Financial Officer.',
      start: 2975.64,
      text: 'In addition, you know, if we were to talk about our gross margin, I think acquisitions obviously played the largest component of our outperformance this quarter and drove the company as a total on a consolidated basis higher.',
    },
    {
      end: 3004.04,
      speaker: 'John Guthrie, Executive Vice President and Chief Financial Officer.',
      start: 2991.04,
      text: 'We did see negative gross margins in the base business because of that roll-off of the inventory profits, if you will, or that price realization benefit we saw last year.',
    },
    {
      end: 3006.16,
      speaker: 'John Guthrie, Executive Vice President and Chief Financial Officer.',
      start: 3004.04,
      text: 'That will continue into Q2.',
    },
    {
      end: 3013.88,
      speaker: 'John Guthrie, Executive Vice President and Chief Financial Officer.',
      start: 3006.16,
      text: 'I would say in general also freight came a little bit higher than expectations in Q1.',
    },
    {
      end: 3016.32,
      speaker: 'John Guthrie, Executive Vice President and Chief Financial Officer.',
      start: 3013.88,
      text: 'Some of that may continue to Q2.',
    },
    {
      end: 3051.44,
      speaker: 'John Guthrie, Executive Vice President and Chief Financial Officer.',
      start: 3016.32,
      text: "Price cost was also a little bit better, not obviously enough to overcome the price realization benefit in the base business, but in Q2, some of that may – as we get into the season, some of that outperformance kind of on the positive side, I think we're seeing a little of that kind of go back to where we thought it was going to be, so that will be not a headwind but kind of falling more into expectations.",
    },
    {
      end: 3059.28,
      speaker: 'John Guthrie, Executive Vice President and Chief Financial Officer.',
      start: 3051.44,
      text: 'So I think Q2 could still be a very challenging quarter for us on a year-over-year basis and a gross margin.',
    },
    {
      end: 3069.16,
      speaker: 'John Guthrie, Executive Vice President and Chief Financial Officer.',
      start: 3059.28,
      text: "I would say in general the second half of the year will be in a better position, as we've talked about previously.",
    },
    {
      end: 3070.16,
      speaker: 'Joy,  Deutsche Bank',
      start: 3069.16,
      text: 'Okay, great.',
    },
    {
      end: 3072.64,
      speaker: 'Joy,  Deutsche Bank',
      start: 3070.16,
      text: 'Thanks so much for that additional detail.',
    },
    {
      end: 3084.72,
      speaker: 'Joy,  Deutsche Bank',
      start: 3072.64,
      text: "My second question, if we go back to the organic sales commentary, I imagine you didn't give April necessarily for us to extrapolate, but maybe just to contextualize the first quarter weather impact.",
    },
    {
      end: 3095.7599999999998,
      speaker: 'Joy,  Deutsche Bank',
      start: 3084.72,
      text: 'So is a better way to kind of get there to think about the second quarter as roughly being 30 percent or so of your full-year dollar sales?',
    },
    {
      end: 3104.76,
      speaker: 'Joy,  Deutsche Bank',
      start: 3095.7599999999998,
      text: 'Is that sort of in the range of your expectations for Q2?',
    },
    {
      end: 3123.88,
      speaker: 'Doug Black, CEO',
      start: 3104.76,
      text: 'I think the second and third quarters are typically at 30 apiece, kind of 60, and then you get 20 and 20 roughly in the first and fourth, roughly, plus or minus.',
    },
    {
      end: 3129.4,
      speaker: 'Joy,  Deutsche Bank',
      start: 3123.88,
      text: 'Okay, thanks a lot, guys.',
    },
    {
      end: 3135.12,
      speaker: 'Operator ',
      start: 3129.4,
      text: 'Our next question comes from Stephen Borgman with Jeffery.',
    },
    {
      end: 3136.52,
      speaker: 'Stephen Borgman, Jeffery',
      start: 3135.12,
      text: 'Hi, good morning, guys.',
    },
    {
      end: 3143.08,
      speaker: 'Stephen Borgman, Jeffery',
      start: 3136.52,
      text: 'John, I think you mentioned a little bit more seasonal inventory build this year surprised me a little bit.',
    },
    {
      end: 3145.4,
      speaker: 'Stephen Borgman, Jeffery',
      start: 3143.08,
      text: 'Can you just comment on that a little bit more?',
    },
    {
      end: 3155,
      speaker: 'John Guthrie, Executive Vice President and Chief Financial Officer.',
      start: 3145.4,
      text: 'Yeah, so we went into this year, we did bring in more inventory, a little bit more inventory.',
    },
    {
      end: 3166.32,
      speaker: 'John Guthrie, Executive Vice President and Chief Financial Officer.',
      start: 3155,
      text: "Obviously, price is contributing to that, I think it's probably four or five percent of that increase year over year in our base business is due to price.",
    },
    {
      end: 3180.46,
      speaker: 'John Guthrie, Executive Vice President and Chief Financial Officer.',
      start: 3166.32,
      text: "And then the other thing, and I'm primarily thinking this from a cash flow perspective, the other thing that's playing into there, obviously, we brought it in, those sales in the north were delayed from that perspective.",
    },
    {
      end: 3193.84,
      speaker: 'John Guthrie, Executive Vice President and Chief Financial Officer.',
      start: 3180.46,
      text: 'So our spring load, those weather, resulted in slightly higher than I think our original plan was because of those sales were delayed.',
    },
    {
      end: 3227.1600000000003,
      speaker: 'John Guthrie, Executive Vice President and Chief Financial Officer.',
      start: 3193.84,
      text: "But in general, I think our goal is to have our stores fully stocked, this is kind of game time, if you will, for our branches and our customers, and we want to be there with the product, but it also allows us as we get into the second half of the year, the opportunity to optimize that better, and we think there's an opportunity over the course of the full year to improve our inventory terms and our working capital.",
    },
    {
      end: 3229.6400000000003,
      speaker: 'Stephen Borgman, Jeffery',
      start: 3227.1600000000003,
      text: 'Great, thank you for that.',
    },
    {
      end: 3237.6,
      speaker: 'Stephen Borgman, Jeffery',
      start: 3229.6400000000003,
      text: "And then, Doug, you mentioned in your prepared remarks some comments around credit availability, and you're not really seeing any issues.",
    },
    {
      end: 3251.36,
      speaker: 'Stephen Borgman, Jeffery',
      start: 3237.6,
      text: 'I was hoping I could pull on that a little bit, because I could imagine that some of your contractor customers might have some issues with credit, possibly, in this type of environment.',
    },
    {
      end: 3259.88,
      speaker: 'Stephen Borgman, Jeffery',
      start: 3251.36,
      text: 'And then, secondarily, I can imagine maybe that some of your M&A targets could potentially have some issues.',
    },
    {
      end: 3266.32,
      speaker: 'Stephen Borgman, Jeffery',
      start: 3259.88,
      text: 'So maybe both of those topics, I wonder if those are any concern for you.',
    },
    {
      end: 3273.32,
      speaker: 'Doug Black, CEO',
      start: 3266.32,
      text: "You know, we really haven't run into that, at least to date.",
    },
    {
      end: 3279.44,
      speaker: 'Doug Black, CEO',
      start: 3273.32,
      text: 'Obviously, effects of that could be delayed and roll in in the second half, et cetera.',
    },
    {
      end: 3289.8,
      speaker: 'Doug Black, CEO',
      start: 3279.44,
      text: "But so far, our commercial customers are continuing to do work, and they've got backlogs and projects seem to be coming in.",
    },
    {
      end: 3298.04,
      speaker: 'Doug Black, CEO',
      start: 3289.8,
      text: 'And in terms of acquisitions, we court and target strong companies that are high performers.',
    },
    {
      end: 3303.6800000000003,
      speaker: 'Doug Black, CEO',
      start: 3298.04,
      text: "And so they aren't the ones that end up with issues.",
    },
    {
      end: 3310.84,
      speaker: 'Doug Black, CEO',
      start: 3303.6800000000003,
      text: "The companies out there that have issues are probably not on our target list, because they're the weaker performers in the market.",
    },
    {
      end: 3313.92,
      speaker: 'Doug Black, CEO',
      start: 3310.84,
      text: "And so we haven't seen that as well.",
    },
    {
      end: 3318.68,
      speaker: 'Doug Black, CEO',
      start: 3313.92,
      text: 'And as Scott mentioned, the deal flow has been steady and consistent.',
    },
    {
      end: 3328.52,
      speaker: 'Doug Black, CEO',
      start: 3318.68,
      text: "We haven't seen any rush to us, and we haven't seen any falloff having to do with higher interest rates or credit.",
    },
    {
      end: 3329.52,
      speaker: 'John Guthrie, Executive Vice President and Chief Financial Officer',
      start: 3328.52,
      text: 'Super.',
    },
    {
      end: 3330.52,
      speaker: 'Stephen Borgman, Jeffery',
      start: 3329.52,
      text: 'Thanks.',
    },
    {
      end: 3331.52,
      speaker: 'Stephen Borgman, Jeffery',
      start: 3330.52,
      text: "I'll pass it on.",
    },
    {
      end: 3332.52,
      speaker: 'Stephen Borgman, Jeffery',
      start: 3331.52,
      text: 'Appreciate it.',
    },
    {
      end: 3342.24,
      speaker: 'Operator ',
      start: 3332.52,
      text: 'We are closing our question and answer session.',
    },
    {
      end: 3347.24,
      speaker: 'Operator ',
      start: 3342.24,
      text: 'Now I would like to turn the floor back over to Doug Black for closing comments.',
    },
    {
      end: 3348.8399999999997,
      speaker: 'Operator ',
      start: 3347.24,
      text: 'Please go ahead.',
    },
    {
      end: 3349.8399999999997,
      speaker: 'John Guthrie, Executive Vice President and Chief Financial Officer',
      start: 3348.8399999999997,
      text: 'Okay.',
    },
    {
      end: 3352.9599999999996,
      speaker: 'Doug Black, CEO',
      start: 3349.8399999999997,
      text: 'Well, thank you again for joining us today.',
    },
    {
      end: 3361,
      speaker: 'Doug Black, CEO',
      start: 3352.9599999999996,
      text: 'We very much appreciate your interest in Site 1 and look forward to speaking to you again in our next quarterly earnings call.',
    },
    {
      end: 3372.64,
      speaker: 'Doug Black, CEO',
      start: 3361,
      text: 'I would like to give another special thanks to our terrific associates for the great job that they do, our customers for allowing us to be their partner, and our suppliers for supporting us so well.',
    },
    {
      end: 3376.36,
      speaker: 'Doug Black, CEO',
      start: 3372.64,
      text: 'Thank you, and have a nice day.',
    },
    {
      end: 3378.84,
      speaker: 'Operator ',
      start: 3376.36,
      text: "This concludes today's conference call.",
    },
    {
      end: 3381.12,
      speaker: 'Operator ',
      start: 3378.84,
      text: 'You may disconnect your lines at this time.',
    },
    {
      end: 3408.12,
      speaker: 'Operator ',
      start: 3381.12,
      text: 'Thank you for your participation, and have a great day.',
    },
  ],
};
